name: dart_code_metrics
version: 5.7.0
description: Software analytics tool that helps developers analyse and improve software quality.
homepage: https://dcm.dev
repository: https://github.com/dart-code-checker/dart-code-metrics
issue_tracker: https://github.com/dart-code-checker/dart-code-metrics/issues
documentation: https://dcm.dev/docs/individuals/getting-started

# flutter: ">=3.22.0"
environment:
  sdk: ">=2.12.0 <4.0.0"

platforms:
  linux:
  windows:
  macos:

dependencies:
  analyzer: #^5.13.0
  analyzer_plugin: #^0.11.2
  ansicolor: #^2.0.1
  args: #^2.0.0
  collection: #^1.16.0
  crypto: #^3.0.0
  dart_code_metrics_presets: #^2.7.0
  file: #">=6.0.0 <9.0.0"
  glob: #^2.0.1
  html: #">=0.15.0 <1.0.0"
  http: #^1.1.0
  meta: #^1.9.0
  path: #^1.8.0
  platform: #^3.1.0 # overridden for lowest versions compatibility
  pub_updater: #^0.4.0
  source_span: #^1.8.0
  uuid: #^4.2.2
  xml: #">=5.3.0 <7.0.0"
  yaml: #^3.1.0

dev_dependencies:
  coverage: #^1.0.2
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  intl: #^0.19.0
  lints: #^3.0.0
  mocktail: #^1.0.2
  test: #^1.21.0

  # internal package, used only in tests data
  test_lints:
    path: ./test/resources/test_lints

executables:
  metrics:
